include: "src/common.smk"
include: "src/align.smk"
include: "src/somatic.smk"
include: "src/qc.smk"

rule all:
	input:
		"results/qc/multiqc/multiqc_report.html",
		expand(['results/vcf/{tumor}_filt.vcf'], tumor = tumor_samples)
